#!/bin/bash
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi


if [ -d $HOME/.bashrc-source ]
then
	for file in $HOME/.bashrc-source/*
	do
		source $file
	done
fi

if [ -n "$DISPLAY" ]  # interactive settings, if a Xserver is running
then
	xset b off  # don't use that annoying beep!
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# according to man 1 gpg-agent, this should be set
export GPG_TTY=$(tty)
